//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_Form
    {
        public int Id { get; set; }
        public string MaForm { get; set; }
        public string TenForm { get; set; }
        public Nullable<int> IDGroup { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<int> IDChucNangCha { get; set; }
        public Nullable<bool> Xem { get; set; }
        public Nullable<bool> Them { get; set; }
        public Nullable<bool> Sua { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public Nullable<bool> IsButtonPhanQuyen { get; set; }
        public string ThamSo { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<bool> IsShowDialog { get; set; }
        public string Image { get; set; }
    }
}
