//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_Page
    {
        public int Id { get; set; }
        public string MaPage { get; set; }
        public string TenPage { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<int> STT { get; set; }
    }
}
